name: Deploy FE Yestech

on:
  push:
    branches:
      - Main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/Fe-Yestech

            git reset --hard
            git clean -fd
            git pull origin Main

            npm install
            npm run build
            pm2 restart fe-user
